worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    upstream gunicorn {
        server 127.0.0.1:8000;
    }

    server {
        listen 8080;
        server_name localhost;

        location /public/ {
            alias /mnt/c/src/GitHub/2026-MAI-Backend-O-Silaeva/lab2/public/;
            autoindex on;
            expires 1d;
            add_header Cache-Control "public, immutable";
        }

        location /gunicorn {
            proxy_pass http://gunicorn/;
            proxy_set_header Host $host;
            proxy_set_header X-Real_IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            return 200 "Nginx works!";
            add_header Content-Type text/plain;
        }
    }
}